[supervisord]
nodaemon=true

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
priority=10

[program:postfix]
command=/usr/lib/postfix/sbin/master -d
autorestart=true
priority=20

[program:dovecot]
command=/usr/sbin/dovecot -F
autorestart=true
priority=30
